#!/usr/bin/env bash

for v in *.gz; do
    SAMPLE=$(echo $v | cut -d . -f 1)

    gunzip -c $v |
        awk -v SAMPLE=$SAMPLE 'BEGIN {FS="\t"} !/^#/ { printf("%s\t%s\t%d\t%s\t%s\t%s\t%s:%d\n", SAMPLE, $1, $2, $3, $4, $5, $1, $2) }' >$SAMPLE.tsv
done
