#!/usr/bin/env bash

SAMPLE=$1

# download the reference data
if [[ ! -d $HOME/reference/sars-cov-2/nextclade-data/sars-cov-2 ]]; then
    nextclade dataset get --name='sars-cov-2' --output-dir=$HOME/reference/sars-cov-2/nextclade-data/sars-cov-2
fi

if [[ -n ${HOME}/pipeline/sars-cov-2/${SAMPLE}.tgz ]]; then
    echo Starting ${SAMPLE} run

    # give us a place to work
    mkdir -p ${HOME}/pipeline/sars-cov-2/${SAMPLE}

    # build the pipeline
    python ${HOME}/pipeline-builder/sars-cov-2/build_sars_cov2_pe_pipeline.py \
        --cores 72 \
        --sample ${SAMPLE} \
        --work-dir ${HOME} \
        --reference-dir ${HOME}/reference/sars-cov-2 \
        --pipeline-dir ${HOME}/pipeline/sars-cov-2/${SAMPLE} \
        --stats-dir ${HOME}/pipeline/sars-cov-2/${SAMPLE} \
        --script ${HOME}/pipeline/sars-cov-2/${SAMPLE}/${SAMPLE}_runner \
        --temp-dir ${HOME}/stats/temp \
        --fastq-dir ${HOME}/pipeline/FASTQ \
        --caller bcftools \
        --aligner bwa \
        --preprocessor fastp \
        --sorter samtools

    # run the pipeline
    bash ${HOME}/pipeline/sars-cov-2/${SAMPLE}/${SAMPLE}_runner >${HOME}/pipeline/sars-cov-2/${SAMPLE}/${SAMPLE}.log 2>&1

    echo Run ${SAMPLE} completed, packaging

    # pack up the stuff and clean house
    # rm -f ${HOME}/pipeline/sars-cov-2/${SAMPLE}/${SAMPLE}_R1.trimmed.fastq.gz
    # rm -f ${HOME}/pipeline/sars-cov-2/${SAMPLE}/${SAMPLE}_R2.trimmed.fastq.gz

    cd ${HOME}/pipeline/sars-cov-2/
    tar cfz ${HOME}/pipeline/sars-cov-2/${SAMPLE}.tgz ./${SAMPLE}
    # rm -rf ${HOME}/pipeline/sars-cov-2/${SAMPLE}

    echo Finished ${SAMPLE} run
else
    echo "We have already processed sample ${SAMPLE}"
fi
