#!/usr/bin/env bash

SAMPLE=$1

echo ${SAMPLE}

if [[ -n ${HOME}/pipeline/${SAMPLE}.tar ]]; then
    # give us a place to work
    mkdir -p ${HOME}/pipeline/${SAMPLE}

    # build the pipeline
    python ${HOME}/pipeline-builder/human/build-hg38-pipeline.py \
        --sample ${SAMPLE} \
        --work-dir ${HOME} \
        --reference-dir ${HOME}/reference/GRCh38.p14 \
        --reference-assembly GCF_000001405.40_GRCh38.p14_genomic \
        --sizes ${HOME}/pipeline-builder/human/GRCh38-p14-chromosomeSizes.json \
        --pipeline-dir ${HOME}/pipeline/${SAMPLE} \
        --stats-dir ${HOME}/pipeline/${SAMPLE} \
        --script ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_runner \
        --skip-alignment-qc \
        --temp-dir ${HOME}/stats/temp \
        --fastq-dir ${HOME}/pipeline/FASTQ 
   
    # run the pipeline
    bash ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_runner >${HOME}/pipeline/${SAMPLE}/${SAMPLE}.log 2>&1

    # rm -f ${HOME}/pipeline/${SAMPLE}/${SAMPLE}.aligned.sam.gz
    # rm -f ${HOME}/pipeline/${SAMPLE}/${SAMPLE}.sorted.bam

    # pushd ${HOME}/pipeline/
    # tar -cvf ${HOME}/pipeline/${SAMPLE}.tar ./${SAMPLE}
    # popd

    # rm -rf ${HOME}/pipeline/${SAMPLE}
else
    echo "We have already processed sample ${SAMPLE}"
fi
