#!/usr/bin/env bash

SAMPLE=$1

echo ${SAMPLE}

if [[ -n ${HOME}/pipeline/${SAMPLE}.tar ]]; then
    # give us a place to work
    mkdir -p ${HOME}/pipeline/${SAMPLE}

    # build the pipeline
    python ${HOME}/pipeline-builder/human/build-hg38-pipeline.py \
        --sample ${SAMPLE} \
        --work-dir ${HOME} \
        --reference-dir ${HOME}/reference \
        --reference-assembly Homo_sapiens_T2T_CHM13_v2 \
        --sizes ${HOME}/pipeline-builder/human/chm13-chromosomeSizes.json \
        --pipeline-dir ${HOME}/pipeline/${SAMPLE} \
        --stats-dir ${HOME}/pipeline/${SAMPLE} \
        --script ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_runner \
        --temp-dir ${HOME}/stats/temp \
        --fastq-dir ${HOME}/stats/FASTQ \
        --align-only \
        --clean 
    
    # run the pipeline
    bash ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_runner >${HOME}/pipeline/${SAMPLE}/${SAMPLE}.log 2>&1
    exit

    rm -f ${HOME}/pipeline/${SAMPLE}/${SAMPLE}.aligned.sam.gz
    rm -f ${HOME}/pipeline/${SAMPLE}/${SAMPLE}.sorted.bam

    pushd ${HOME}/pipeline/
    tar -cvf ${HOME}/pipeline/${SAMPLE}.tar ./${SAMPLE}
    popd

    rm -rf ${HOME}/pipeline/${SAMPLE}
else
    echo "We have already processed sample ${SAMPLE}"
fi
