#!/usr/bin/env bash

set -e -o pipefail

# installables
if [[ -z "${SKIP_BREW}" ]]; then
    brew install \
        cmake \
        gcc \
        boost \
        dwdiff wdiff \
        nasm \
        libgit2 \
        llvm \
        autoconf \
        gsl \
        pkg-config \
        libomp \
        gnu-sed \
        jsoncpp
fi

ROOT_DIR=${HOME}/pipeline

mkdir -p ${ROOT_DIR}

mkdir -p \
    ${ROOT_DIR}/components \
    ${ROOT_DIR}/src \
    ${ROOT_DIR}/output \
    ${ROOT_DIR}/bin \
    ${ROOT_DIR}/lib \
    ${ROOT_DIR}/include \
    ${ROOT_DIR}/libexec \
    ${ROOT_DIR}/share \
    ${ROOT_DIR}/stats \
    ${ROOT_DIR}/tmp \
    ${ROOT_DIR}/perl5 \
    ${ROOT_DIR}/reference

# samtools / bamtools / bedtools
curl --silent https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2 --location -o ${ROOT_DIR}/components/htslib.tgz &&
    tar xf ${ROOT_DIR}/components/htslib.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/htslib-1.21 ${ROOT_DIR}/src/htslib

curl --silent https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 --location -o ${ROOT_DIR}/components/samtools.tgz &&
    tar xf ${ROOT_DIR}/components/samtools.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/samtools-1.21 ${ROOT_DIR}/src/samtools

curl --silent https://github.com/samtools/bcftools/releases/download/1.21/bcftools-1.21.tar.bz2 --location -o ${ROOT_DIR}/components/bcftools.tgz &&
    tar xf ${ROOT_DIR}/components/bcftools.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/bcftools-1.21 ${ROOT_DIR}/src/bcftools

curl --silent https://github.com/pezmaster31/bamtools/archive/refs/tags/v2.5.2.tar.gz --location -o ${ROOT_DIR}/components/bamtools.tgz &&
    tar xf ${ROOT_DIR}/components/bamtools.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/bamtools-2.5.2 ${ROOT_DIR}/src/bamtools

curl --silent https://github.com/arq5x/bedtools2/releases/download/v2.31.1/bedtools-2.31.1.tar.gz --location -o ${ROOT_DIR}/components/bedtools.tgz &&
    tar xf ${ROOT_DIR}/components/bedtools.tgz -C ${ROOT_DIR}/src

# aligners and other stuff
rm -rf ${ROOT_DIR}/src/bwa && git clone https://github.com/lh3/bwa.git ${ROOT_DIR}/src/bwa
rm -rf ${ROOT_DIR}/src/bwa-mem2 && git clone --recursive https://github.com/bwa-mem2/bwa-mem2.git ${ROOT_DIR}/src/bwa-mem2
rm -rf ${ROOT_DIR}/src/star && git clone https://github.com/alexdobin/STAR.git ${ROOT_DIR}/src/star
rm -rf ${ROOT_DIR}/src/hisat2 && git clone https://github.com/DaehwanKimLab/hisat2.git ${ROOT_DIR}/src/hisat2
rm -rf ${ROOT_DIR}/src/regtools && git clone https://github.com/griffithlab/regtools ${ROOT_DIR}/src/regtools

curl --silent https://github.com/COMBINE-lab/salmon/archive/refs/tags/v1.10.3.tar.gz --location -o ${ROOT_DIR}/components/salmon.tgz &&
    tar xf ${ROOT_DIR}/components/salmon.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/salmon-1.10.3 ${ROOT_DIR}/src/salmon

curl --silent https://github.com/lh3/minimap2/archive/refs/tags/v2.28.tar.gz --location -o ${ROOT_DIR}/components/minimap2.tgz &&
    tar xf ${ROOT_DIR}/components/minimap2.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/minimap2-2.28 ${ROOT_DIR}/src/minimap2

curl --silent https://bitbucket.org/kokonech/qualimap/downloads/qualimap_v2.3.zip --location -o ${ROOT_DIR}/components/qualimap.zip &&
    unzip -o ${ROOT_DIR}/components/qualimap.zip -d ${ROOT_DIR}/bin &&
    mv ${ROOT_DIR}/bin/qualimap_v2.3 ${ROOT_DIR}/bin/QualiMap

curl --silent https://github.com/vcftools/vcftools/releases/download/v0.1.16/vcftools-0.1.16.tar.gz --location -o ${ROOT_DIR}/components/vcftools.tgz &&
    tar xf ${ROOT_DIR}/components/vcftools.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/vcftools-0.1.16 ${ROOT_DIR}/src/vcftools

curl --silent https://github.com/shenwei356/seqkit/releases/download/v2.8.2/seqkit_darwin_amd64.tar.gz --location -o ${ROOT_DIR}/components/seqkit.tgz &&
    tar xf ${ROOT_DIR}/components/seqkit.tgz -C ${ROOT_DIR}/bin

curl --silent https://github.com/usadellab/Trimmomatic/files/5854859/Trimmomatic-0.39.zip --location -o ${ROOT_DIR}/components/trimmomatic.zip &&
    unzip -o ${ROOT_DIR}/components/trimmomatic.zip -d ${ROOT_DIR}/bin &&
    mv ${ROOT_DIR}/bin/Trimmomatic-0.39 ${ROOT_DIR}/bin/Trimmomatic

# gatk and picard
curl --silent https://github.com/broadinstitute/gatk/releases/download/4.6.0.0/gatk-4.6.0.0.zip --location -o ${ROOT_DIR}/components/gatk.zip &&
    unzip -o ${ROOT_DIR}/components/gatk.zip -d ${ROOT_DIR}/bin &&
    mv ${ROOT_DIR}/bin/gatk-4.6.0.0 ${ROOT_DIR}/bin/GATK

curl --silent https://github.com/broadinstitute/picard/releases/download/3.2.0/picard.jar --location -o ${ROOT_DIR}/bin/picard.jar

# other supporting tools
curl --silent https://gitlab.com/german.tischler/libmaus2/-/archive/2.0.813-release-20221210220409/libmaus2-2.0.813-release-20221210220409.tar.gz --location -o ${ROOT_DIR}/components/libmaus2.tgz &&
    tar xf ${ROOT_DIR}/components/libmaus2.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/libmaus2-2.0.813-release-20221210220409 ${ROOT_DIR}/src/libmaus2

curl --silent https://gitlab.com/german.tischler/biobambam2/-/archive/2.0.185-release-20221211202123/biobambam2-2.0.185-release-20221211202123.tar.gz --location -o ${ROOT_DIR}/components/biobambam2.tgz &&
    tar xf ${ROOT_DIR}/components/biobambam2.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/biobambam2-2.0.185-release-20221211202123 ${ROOT_DIR}/src/biobambam2

curl --silent https://github.com/FelixKrueger/TrimGalore/archive/refs/tags/0.6.10.tar.gz --location -o ${ROOT_DIR}/components/TrimGalore.tgz &&
    tar xf ${ROOT_DIR}/components/TrimGalore.tgz -C ${ROOT_DIR}/bin &&
    mv ${ROOT_DIR}/bin/TrimGalore-0.6.10 ${ROOT_DIR}/bin/TrimGalore

curl --silent https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip --location -o ${ROOT_DIR}/components/fastqc.zip &&
    unzip -o ${ROOT_DIR}/components/fastqc.zip -d ${ROOT_DIR}/bin

# compression utilities
curl --silent https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.2.2.tar.gz --location -o ${ROOT_DIR}/components/zlib-ng.tgz &&
    tar xf ${ROOT_DIR}/components/zlib-ng.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/zlib-ng-2.2.2 ${ROOT_DIR}/src/zlib-ng

curl --silent https://zlib.net/zlib-1.3.1.tar.gz --location -o ${ROOT_DIR}/components/zlib.tgz &&
    tar xf ${ROOT_DIR}/components/zlib.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/zlib-1.3.1 ${ROOT_DIR}/src/zlib

curl --silent https://github.com/madler/pigz/archive/refs/tags/v2.8.tar.gz --location -o ${ROOT_DIR}/components/pigz.tgz &&
    tar xf ${ROOT_DIR}/components/pigz.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/pigz-2.8 ${ROOT_DIR}/src/pigz

curl https://github.com/cli/cli/releases/download/v2.58.0/gh_2.58.0_macOS_amd64.zip --location -o ${ROOT_DIR}/components/gh.zip &&
    unzip -o ${ROOT_DIR}/components/gh.zip -d ${ROOT_DIR}/components &&
    cp -r ${ROOT_DIR}/components/gh_2.58.0_macOS_amd64/share/* ${ROOT_DIR}/share &&
    cp ${ROOT_DIR}/components/gh_2.58.0_macOS_amd64/bin/gh ${ROOT_DIR}/bin

# variant annotators
curl --silent https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip --location -o ${ROOT_DIR}/components/snpEff_latest_core.zip
echo "Downloading nextclade"
system=$(uname -s)
arch=$(uname -m)

if [[ ! -f nextclade ]]; then
    if [[ "${system}" == "Darwin" ]]; then
        if [[ "${arch}" == "x86_64" ]]; then
            echo "Downloading nextclade for Intel MacOS"
            curl --silent https://github.com/nextstrain/nextclade/releases/download/3.8.2/nextclade-x86_64-apple-darwin --location -o ${ROOT_DIR}/bin/nextclade &&
                chmod +x ${ROOT_DIR}/bin/nextclade
        else
            echo "Downloading nextclade for ARM MacOS"
            curl --silent https://github.com/nextstrain/nextclade/releases/download/3.8.2/nextclade-aarch64-apple-darwin --location -o ${ROOT_DIR}/bin/nextclade &&
                chmod +x ${ROOT_DIR}/bin/nextclade
        fi
    elif [[ "${system}" == "Linux" ]]; then
        if [[ "${arch}" == "x86_64" ]]; then
            echo "Downloading nextclade for Intel Linux"
            curl --silent https://github.com/nextstrain/nextclade/releases/download/3.8.2/nextclade-x86_64-unknown-linux-gnu --location -o ${ROOT_DIR}/bin/nextclade &&
                chmod +x ${ROOT_DIR}/bin/nextclade
        else
            echo "Downloading nextclade for ARM Linux"
            curl --silent https://github.com/nextstrain/nextclade/releases/download/3.8.2/nextclade-aarch64-unknown-linux-gnu --location -o ${ROOT_DIR}/bin/nextclade &&
                chmod +x ${ROOT_DIR}/bin/nextclade
        fi
    else
        echo "Nextclade not supported on your platform, maybe"
    fi
fi

curl --silent https://github.com/Illumina/Nirvana/archive/refs/tags/v3.18.1.tar.gz --location -o ${ROOT_DIR}/components/nirvana.tgz &&
    tar xf ${ROOT_DIR}/components/nirvana.tgz -C ${ROOT_DIR}/src &&
    mv ${ROOT_DIR}/src/Nirvana-3.18.1 ${ROOT_DIR}/src/Nirvana
