#!/usr/bin/env bash

SAMPLE=$1

if [[ -n ${HOME}/pipeline/${SAMPLE}.tar ]]; then
    echo Starting ${SAMPLE} run

    # give us a place to work
    mkdir -p ${HOME}/pipeline/${SAMPLE}

    # build the pipeline
    python ${HOME}/pipeline-builder/hcov-229e/build_hcov_229e_pe_pipeline.py \
        --cores 8 \
        --sample ${SAMPLE} \
        --work-dir ${HOME} \
        --pipeline-dir ${HOME}/pipeline/${SAMPLE} \
        --stats-dir ${HOME}/pipeline/${SAMPLE} \
        --script ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_runner \
        --temp-dir ${HOME}/stats/temp \
        --fastq-dir ${HOME}/pipeline/FASTQ \
        --caller bcftools \
        --aligner hisat2 \
        --preprocessor trimmomatic \
        --sorter samtools

    # run the pipeline
    bash ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_runner >${HOME}/pipeline/${SAMPLE}/${SAMPLE}.log 2>&1

    # pack up the stuff and clean house
    rm -f ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_R1.trimmed.fastq.gz
    rm -f ${HOME}/pipeline/${SAMPLE}/${SAMPLE}_R2.trimmed.fastq.gz

    cd ${HOME}/pipeline/
    tar cfz ${HOME}/pipeline/${SAMPLE}.tgz ./${SAMPLE}
    # rm -rf ${HOME}/pipeline/${SAMPLE}

    echo Finished ${SAMPLE} run
else
    echo "We have already processed sample ${SAMPLE}"
fi
