#!/usr/bin/env bash

echo "This script uses a handful of, well, interesting build components that "
echo "do not come standard on MacOS. So, before you get started you'll want to"
echo ""
echo "brew install cmake jsoncpp gcc-11 boost nasm libgit2"
echo ""

ROOT=$(pwd)

mkdir -p \
    src \
    output \
    bin \
    stats \
    components \
    tmp \
    perl5

mkdir -p \
    reference/GRCh38.p14 \
    reference/hcov-229e \
    reference/hcov-emc \
    reference/hcov-hku1 \
    reference/hcov-nl63 \
    reference/hcov-oc43 \
    reference/hcov-panel \
    reference/sars-cov-2 \
    reference/vep-data

# get a couple of tools for later
cd ${ROOT}/bin

curl -L -O http://xrl.us/cpanm >cpanm
chmod 755 cpanm

pip install --upgrade pip setuptools
pip install --user cutadapt
pip install --user bgzip

# download and unpack
cd ${ROOT}/components

echo "Downloading SAMTOOLS components"
if [[ ! -f samtools-1.16.tar.bz2 ]]; then
    curl --silent https://github.com/samtools/samtools/releases/download/1.16/samtools-1.16.tar.bz2 --location -O
fi

if [[ ! -f bcftools-1.16.tar.bz2 ]]; then
    curl --silent https://github.com/samtools/bcftools/releases/download/1.16/bcftools-1.16.tar.bz2 --location -O
fi

if [[ ! -f htslib-1.16.tar.bz2 ]]; then
    curl --silent https://github.com/samtools/htslib/releases/download/1.16/htslib-1.16.tar.bz2 --location -O
fi

echo "Downloading BAMTOOLS components"
if [[ ! -f bamtools.tgz ]]; then
    curl --silent https://github.com/pezmaster31/bamtools/archive/refs/tags/v2.5.2.tar.gz --location -o bamtools.tgz
fi

echo "Downloading BEDTOOLS components"
if [[ ! -d ${ROOT}/src/bedtools2 ]]; then
    git clone git@github.com:arq5x/bedtools2.git ${ROOT}/src/bedtools2
fi

echo "Downloading BWA & BWA-MEM2"
if [[ ! -f bwa-0.7.17.tar.bz2 ]]; then
    curl --silent https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2 --location -O
fi

if [[ ! -d ${ROOT}/src/bwa-mem2 ]]; then
    git clone --recursive https://github.com/bwa-mem2/bwa-mem2 ${ROOT}/src/bwa-mem2
fi

echo "Downloading GATK and picard"
if [[ ! -f picard.jar ]]; then
    curl --silent https://github.com/broadinstitute/picard/releases/download/2.27.4/picard.jar --location -O
fi

if [[ ! -f gatk-4.2.6.1.zip ]]; then
    curl --silent https://github.com/broadinstitute/gatk/releases/download/4.2.6.1/gatk-4.2.6.1.zip --location -O
fi

echo "Downloading FASTQC"
if [[ ! -f fastqc_v0.11.9.zip ]]; then
    curl --silent https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip --location -O
fi

echo "Downloading BIOBAMBAM components"
if [[ ! -f libmaus2-2.0.810-release-20220216151520.tar.gz ]]; then
    curl --silent https://gitlab.com/german.tischler/libmaus2/-/archive/2.0.810-release-20220216151520/libmaus2-2.0.810-release-20220216151520.tar.gz --location -O
fi

if [[ ! -f biobambam2-2.0.183-release-20210802180148.tar.gz ]]; then
    curl --silent https://gitlab.com/german.tischler/biobambam2/-/archive/2.0.183-release-20210802180148/biobambam2-2.0.183-release-20210802180148.tar.gz --location -O
fi

echo "Downloading trimgalore"
if [[ ! -f trim_galore.tgz ]]; then
    curl --silent https://github.com/FelixKrueger/TrimGalore/archive/refs/tags/0.6.7.tar.gz --location -o trim_galore.tgz
fi

echo "Downloading compression utilities"
if [[ ! -f zlib-ng.tgz ]]; then
    curl --silent https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.0.6.tar.gz --location -o zlib-ng.tgz
fi

if [[ ! -f pigz.tgz ]]; then
    curl --silent https://github.com/madler/pigz/archive/refs/tags/v2.7.tar.gz --location -o pigz.tgz
fi

if [[ ! -f zlib-1.2.12.tar.gz ]]; then
    curl --silent https://zlib.net/zlib-1.2.12.tar.gz --location -O
fi

echo "Downloading vcftools"
if [[ ! -f vcftools-0.1.16.tar.gz ]]; then
    curl --silent https://github.com/vcftools/vcftools/releases/download/v0.1.16/vcftools-0.1.16.tar.gz --location -O
fi

if [[ ! -d ${ROOT}/src/isa-l ]]; then
    git clone https://github.com/intel/isa-l.git ${ROOT}/src/isa-l
fi

if [[ ! -d ${ROOT}/src/libdeflate ]]; then
    git clone https://github.com/ebiggers/libdeflate.git ${ROOT}/src/libdeflate
fi

if [[ ! -d ${ROOT}/src/fastp ]]; then
    git clone https://github.com/OpenGene/fastp.git ${ROOT}/src/fastp
fi

echo "Downloading snpEff"
if [[ ! -f snpEff_latest_core.zip ]]; then
    curl --silent https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip --location -o ${ROOT}/components/snpEff_latest_core.zip
fi

echo "Downloading nextclade"
system=$(uname -s)
arch=$(uname -m)

if [[ "${system}" == "Darwin" ]]; then
    if [[ "${arch}" == "x86_64" ]]; then
        if [[ ! -f nextclade ]]; then
            echo "Downloading nextclade for Intel MacOS"
            curl --silent https://github.com/nextstrain/nextclade/releases/download/2.4.0/nextclade-x86_64-apple-darwin --location -o nextclade
        fi
    else
        if [[ ! -f nextclade ]]; then
            echo "Downloading nextclade for ARM MacOS"
            curl --silent https://github.com/nextstrain/nextclade/releases/download/2.4.0/nextclade-aarch64-apple-darwin --location -o nextclade
        fi
    fi
elif [[ "${system}" == "Linux" ]]; then
    if [[ ! -f nextclade ]]; then
        echo "Downloading nextclade for Intel Linux"
        curl --silent https://github.com/nextstrain/nextclade/releases/download/2.4.0/nextclade-x86_64-unknown-linux-gnu --location -o nextclade
    fi
else
    echo "Nextclade not supported on your platform, maybe"
fi

#
#
# The following are RNA-seq tools. Some work for all sequence informatics, but they're lumped
# in here to handle a specific protocol
#
#

echo "RNA-seq: Downloading STAR"
if [[ ! -d ${ROOT}/src/STAR ]]; then
    git clone git@github.com:alexdobin/STAR.git ${ROOT}/src/STAR
fi

echo "RNA-seq: Downloading bowtie2"
if [[ ! -d ${ROOT}/src/bowtie2 ]]; then
    git clone git@github.com:BenLangmead/bowtie2.git ${ROOT}/src/bowtie2
fi

# echo "RNA-seq: Downloading tophat"
# if [[ ! -d ${ROOT}/src/tophat ]]; then
#     git clone git@github.com:DaehwanKimLab/tophat.git ${ROOT}/src/tophat
# fi

echo "RNA-seq: Downloading hisat2"
if [[ ! -d ${ROOT}/src/hisat2 ]]; then
    git clone git@github.com:DaehwanKimLab/hisat2.git ${ROOT}/src/hisat2
fi

echo "RNA-seq: Downloading minimap2"
if [[ ! -d ${ROOT}/src/minimap2 ]]; then
    git clone git@github.com:lh3/minimap2.git ${ROOT}/src/minimap2
fi

echo "RNA-seq: Downloading kallisto"
if [[ ! -d ${ROOT}/src/kallisto ]]; then
    git clone https://github.com/pachterlab/kallisto.git ${ROOT}/src/kallisto
fi

echo "RNA-seq: Downloading QualiMap"
curl --silent https://bitbucket.org/kokonech/qualimap/downloads/qualimap_v2.2.1.zip --location -O

##
## unpack and build
##

echo "Unpacking source code"
cd ${ROOT}/src
for t in ${ROOT}/components/*.tgz ${ROOT}/components/*.tar.gz ${ROOT}/components/*.tar.bz2; do
    tar xzf $t
done

for z in ${ROOT}/components/*.zip; do
    unzip -o -qq $z
done

echo "Installing a few standalone / non-build tools"
cp ${ROOT}/components/nextclade ${ROOT}/bin/nextclade && chmod +x ${ROOT}/bin/nextclade
mv ${ROOT}/src/snpEff ${ROOT}/bin/snpEff

echo "Setting environment variables for build (gcc and friends)"
export CCPATH=/usr/local/bin
export CCVERSION=12
export CC=/usr/local/bin/gcc-12
export CXX=/usr/local/bin/g++-12
export CXXCPP=/usr/local/bin/cpp-12
export CFLAGS="-I/usr/local/include -Wno-deprecated-declarations  -Wno-unused-result"
export CXXFLAGS=${CFLAGS}
export LDFLAGS="-L/usr/local/lib"

echo "Building SAMTOOLS components"
cd ${ROOT}/src/htslib-1.16
autoreconf -i
./configure --prefix=${ROOT} --exec-prefix=${ROOT}
make
make install

cd ${ROOT}/src/samtools-1.16
autoheader
autoreconf -Wno-syntax
./configure --prefix=${ROOT} --exec-prefix=${ROOT} --with-htslib=${ROOT}
make
make install

cd ${ROOT}/src/bcftools-1.16
autoheader
autoconf
./configure --enable-libgsl --enable-perl-filters --prefix=${ROOT} --exec-prefix=${ROOT} --with-htslib=${ROOT}
make
make install

echo "Building BAMTOOLS components"
cd ${ROOT}/src/bamtools-2.5.2
mkdir -p build
cd build
cmake -DCMAKE_INSTALL_PREFIX=${ROOT} ..
make
make install

echo "Building BEDTOOLS components"
cd ${ROOT}/src/bedtools2
make prefix=${ROOT}
make install
cp bin/* ${ROOT}/bin

echo "Build BWA components"
cd ${ROOT}/src/bwa-0.7.17
make
cp bwa ${ROOT}/bin

echo "Build BWA-MEM components"
echo "Note: if this fails to build properly you need to apply the patch to ext/strsafelib first"
echo "Note: you must apply the bwa-mem2.patch before compiling this"
cd ${ROOT}/src/bwa-mem2
git submodule init
git submodule update

echo "TODO: apply bwa-mem2.patch"
# git apply --ignore-space-change --ignore-whitespace ~/src/ovation/pipeline-builder/docs/mac-install/bwa-mem2.patch
echo "TODO: apply strsafelib.patch"
# cd ext/safestringlib
# git apply --ignore-space-change --ignore-whitespace ~/src/ovation/pipeline-builder/docs/mac-install/strsafelib.patch

echo "TODO: make"
echo "TODO: cp bwa-* ${ROOT}/bin"

echo "Build zlib, zlib-ng, and pigz components"
cd ${ROOT}/src/zlib-ng-2.0.6
./configure --zlib-compat --native
make
make install prefix=${ROOT}

cd ${ROOT}/src/zlib-1.2.12
./configure --prefix=${ROOT} --eprefix=${ROOT}
make
make install prefix=${ROOT}

cd ${ROOT}/src/pigz-2.7
make
cp pigz ${ROOT}/bin
cp unpigz ${ROOT}/bin

echo "Building vcftools"
cd ${ROOT}/src/vcftools-0.1.16
./configure --prefix=${ROOT} --exec-prefix=${ROOT}
make
make install

echo "Building bedtools"
cd ${ROOT}/bedtools-v2.30.0
make prefix=${ROOT}
make install

echo "Building BIOBAMBAM and components - this'll take a while"
cd ${ROOT}/src/libmaus2-2.0.810-release-20220216151520
./configure --enable-compile-testprograms=no --prefix=${ROOT}
make
make install prefix=${ROOT}

cd ${ROOT}/src/biobambam2-2.0.183-release-20210802180148
./configure --prefix=${ROOT} --with-libmaus2=${ROOT}
make
make install prefix=${ROOT}

echo "Building FASTP and components - this'll take a while"
cd ${ROOT}/src/isa-l
autoreconf --install --symlink -f
./configure --target=darwin --prefix=${ROOT} --libdir=${ROOT}/lib
make
make install

cd ${ROOT}/src/libdeflate
make
make install PREFIX=${ROOT}

echo "Building STAR and other RNA-seq tools"
cd ${ROOT}/src/STAR/source
make STARforMacStatic
cp STAR ${ROOT}/bin

cd ${ROOT}/src/bowtie2
make PREFIX=${ROOT}
make install PREFIX=${ROOT}

# cd ${ROOT}/src/tophat
# make PREFIX=${ROOT}
# cp tophat ${ROOT}/bin

cd ${ROOT}/src/hisat2
make GCC_PREFIX=${CCPATH} GCC_SUFFIX=-${CCVERSION}
HISAT2_BIN_LIST=(hisat2 hisat2-build hisat2-build-s hisat2-build-l hisat2-align-s hisat2-align-l hisat2-inspect hisat2-inspect-s hisat2-inspect-l hisat2-repeat)
for f in ${HISAT2_BIN_LIST}; do cp $f ${ROOT}/bin; done
cp *.py ${ROOT}/bin

cd ${ROOT}/src/minimap2
make
mv minimap2 ${ROOT}/bin

echo "Building fastp last, make sure you applied the patch"
echo "TODO: apply kallisto.patch"

cd ${ROOT}/src/kallisto
rm -rf build && mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=${ROOT}
make
make install

echo "Building fastp last, make sure you applied the patch"
echo "TODO: apply fastp.patch"

cd ${ROOT}/src/fastp
git apply --ignore-space-change --ignore-whitespace ~/src/ovation/pipeline-builder/docs/mac-install/fastp.patch

export CXXFLAGS="-I${ROOT}/include -I/usr/local/include"
export LD_FLAGS="-I${ROOT}/lib -L/usr/local/lib"
make PREFIX=${ROOT}
make install PREFIX=${ROOT}

echo "Installing FASTQC, TrimGalore, GATK and picard"
cp -r ${ROOT}/src/FastQC ${ROOT}/bin/FastQC
chmod 755 ${ROOT}/bin/FastQC/fastqc
cp ${ROOT}/components/picard.jar ${ROOT}/bin
cp -r ${ROOT}/src/gatk-4.2.6.1 ${ROOT}/bin/gatk-4.2.6.1
cp ${ROOT}/src/TrimGalore-0.6.7/trim_galore ${ROOT}/bin

echo "Downloading and installing VEP directly to ${ROOT}/bin"
cd ${ROOT}/src
if [[ ! -d ${ROOT}/src/ensembl-vep ]]; then
    git clone https://github.com/Ensembl/ensembl-vep.git ${ROOT}/bin/ensembl-vep
fi

cd ${ROOT}/bin/ensembl-vep
export PERL5LIB=$PERL5LIB:${ROOT}/cpanm/lib/perl5
${ROOT}/bin/cpanm -l ${ROOT}/perl5 --installdeps .

${ROOT}/bin/cpanm DBI
${ROOT}/bin/cpanm Archive::Zip
${ROOT}/bin/cpanm DBD::mysql

echo "Checking out VEP release 107 and pulling all release 107 data / plugins"
git checkout release/107

perl INSTALL.pl \
    --CACHEDIR ${ROOT}/reference/vep-data \
    --ASSEMBLY GRCh38 \
    --AUTO aclfp \
    --PLUGINS all \
    --NO_HTSLIB \
    --NO_TEST \
    --SPECIES homo_sapiens_merged

#
# python stuff, this should really be in a virtualenv, but this'll do
#
pip install --user HTSeq

#
# and some R stuff, more of the same fun, DESeq2 takes a long time to build / install
#
Rscript <<EOF
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
BiocManager::install("rhdf5")
BiocManager::install("Rsubread")

install.packages("pheatmap")
install.packages("devtools")
install.packages("MASS")

devtools::install_github("pachterlab/sleuth")
EOF
