#!/usr/bin/env bash

SAMPLE=$1
ORGANISM=hcov-emc
ASSEMBLY=GCA_000901155.1_ViralProj183710_genomic
REFNAME=JX869059.2

echo Starting ${SAMPLE} run

# give us a place to work
mkdir -p ${HOME}/pipeline/${SAMPLE}/${ORGANISM}

# build the pipeline
python ${HOME}/pipeline-builder/hcov/hcov-runner.py \
    --no-color \
    --cores 72 \
    --sample ${SAMPLE} \
    --work-dir ${HOME} \
    --reference-dir ${HOME}/reference/${ORGANISM} \
    --reference-assembly ${ASSEMBLY} \
    --reference-name ${REFNAME} \
    --pipeline-dir ${HOME}/pipeline/${SAMPLE}/${ORGANISM} \
    --stats-dir ${HOME}/pipeline/${SAMPLE}/${ORGANISM} \
    --script ${HOME}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner \
    --temp-dir ${HOME}/stats/temp \
    --fastq-dir ${HOME}/pipeline/fastq \
    --skip-multi-qc \
    --skip-variant-qc \
    --skip-fastqc \
    --skip-annotation \
    --caller bcftools \
    --aligner bwa \
    --preprocessor trimgalore \
    --sorter biobambam 

cp ${HOME}/pipeline-builder/assets/software_versions_mqc.html ${HOME}/pipeline/${SAMPLE}/${ORGANISM}
cp ${HOME}/pipeline-builder/assets/ovationlogo.png ${HOME}/pipeline/${SAMPLE}/${ORGANISM}

# run the pipeline
bash ${HOME}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner >${HOME}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}.log 2>&1

echo Run ${SAMPLE} completed, packaging

echo Finished ${SAMPLE} run
