#!/usr/bin/env bash

SAMPLE=$1
ORGANISM=sars-cov-2
ASSEMBLY=GCA_009858895.3_ASM985889v3_genomic
REFNAME=MN908947.3

# download the reference data
if [[ ! -d ${HOME}/reference/sars-cov-2/nextclade-data ]]; then
    nextclade dataset get --name='sars-cov-2' --output-dir=${HOME}/reference/sars-cov-2/nextclade-data
fi

echo Starting ${SAMPLE} run

# give us a place to work
mkdir -p ${HOME}/pipeline/${SAMPLE}/${ORGANISM}

# build the pipeline
python ${HOME}/pipeline-builder/hcov/hcov-runner.py \
    --cores 8 \
    --no-color \
    --sample ${SAMPLE} \
    --work-dir ${HOME} \
    --reference-dir ${HOME}/reference/${ORGANISM} \
    --reference-assembly ${ASSEMBLY} \
    --reference-name ${REFNAME} \
    --pipeline-dir ${HOME}/pipeline/${SAMPLE}/${ORGANISM} \
    --stats-dir ${HOME}/pipeline/${SAMPLE}/${ORGANISM} \
    --script ${HOME}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner \
    --temp-dir ${HOME}/stats/temp \
    --fastq-dir ${HOME}/fastq \
    --skip-multi-qc \
    --skip-variant-qc \
    --skip-fastqc \
    --skip-annotation \
    --caller bcftools \
    --aligner bwa \
    --preprocessor trimgalore \
    --sorter biobambam 

cp ${HOME}/pipeline-builder/assets/software_versions_mqc.html ${HOME}/pipeline/${SAMPLE}/${ORGANISM}
cp ${HOME}/pipeline-builder/assets/ovationlogo.png ${HOME}/pipeline/${SAMPLE}/${ORGANISM}

# run the pipeline
bash ${HOME}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner >${HOME}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}.log 2>&1

echo Run ${SAMPLE} completed, packaging

echo Finished ${SAMPLE} run
