#!/usr/bin/env bash

SAMPLE=$1

if [[ -n ${HOME}/pipeline/hcov-oc43/${SAMPLE}.tar ]]; then
    echo Starting ${SAMPLE} run

    # give us a place to work
    mkdir -p ${HOME}/pipeline/hcov-oc43/${SAMPLE}

    # build the pipeline
    python ${HOME}/pipeline-builder/hcov-oc43/build_hcov_oc43_pe_pipeline.py \
        --cores 8 \
        --sample ${SAMPLE} \
        --work-dir ${HOME} \
        --reference-dir ${HOME}/reference/hcov-oc43 \
        --pipeline-dir ${HOME}/pipeline/hcov-oc43/${SAMPLE} \
        --stats-dir ${HOME}/pipeline/hcov-oc43/${SAMPLE} \
        --script ${HOME}/pipeline/hcov-oc43/${SAMPLE}/${SAMPLE}_runner \
        --temp-dir ${HOME}/stats/temp \
        --fastq-dir ${HOME}/pipeline/FASTQ \
        --caller bcftools \
        --aligner bwa \
        --preprocessor none \
        --sorter samtools

    # run the pipeline
    bash ${HOME}/pipeline/hcov-oc43/${SAMPLE}/${SAMPLE}_runner >${HOME}/pipeline/hcov-oc43/${SAMPLE}/${SAMPLE}.log 2>&1

    # pack up the stuff and clean house
    # rm -f ${HOME}/pipeline/hcov-oc43/${SAMPLE}/${SAMPLE}_R1.trimmed.fastq.gz
    # rm -f ${HOME}/pipeline/hcov-oc43/${SAMPLE}/${SAMPLE}_R2.trimmed.fastq.gz

    cd ${HOME}/pipeline/hcov-oc43/
    tar cfz ${HOME}/pipeline/hcov-oc43/${SAMPLE}.tgz ./${SAMPLE}
    # rm -rf ${HOME}/pipeline/hcov-oc43/${SAMPLE}

    echo Finished ${SAMPLE} run
else
    echo "We have already processed sample ${SAMPLE}"
fi
