#!/usr/bin/env bash

sample=$1
pathname=$2

printf "File\tHasCalls\tSample\tOrganism\tAccession\tHash\tDistance\n" >${pathname}/${sample}-consensus-report.tsv

~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-229e (AF304460.1)" ${pathname}/${sample}.hcov-229e.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-nl63 (AY567487.2)" ${pathname}/${sample}.hcov-nl63.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-hku1 (AY597011.2)" ${pathname}/${sample}.hcov-hku1.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-oc43-ay391777 (AY391777.1)" ${pathname}/${sample}.hcov-oc43-ay391777.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-oc43 (AY585228.1)" ${pathname}/${sample}.hcov-oc43.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
