#!/usr/bin/env bash

sample=$1
pathname=$2

printf "File\tHasCalls\tSample\tOrganism\tAccession\tHash\tDistance\n" >${pathname}/${sample}-consensus-report.tsv

if [[ "${sample}" == *"freebayes"* ]]; then
    sample=$(echo $sample | sed 's/.freebayes//')

    ~/pipeline/pipeline-builder/tools/fasta-hash.py "sars-cov-2 (MN908947.3)" ${pathname}/${sample}-sars-cov-2.freebayes.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-229e (AF304460.1)" ${pathname}/${sample}-hcov-229e.freebayes.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-nl63 (AY567487.2)" ${pathname}/${sample}-hcov-nl63.freebayes.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-hku1 (AY597011.2)" ${pathname}/${sample}-hcov-hku1.freebayes.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-oc43 (AY585228.1)" ${pathname}/${sample}-hcov-oc43.freebayes.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
else
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "sars-cov-2 (MN908947.3)" ${pathname}/${sample}-sars-cov-2.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-229e (AF304460.1)" ${pathname}/${sample}-hcov-229e.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-nl63 (AY567487.2)" ${pathname}/${sample}-hcov-nl63.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-hku1 (AY597011.2)" ${pathname}/${sample}-hcov-hku1.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
    ~/pipeline/pipeline-builder/tools/fasta-hash.py "hcov-oc43 (AY585228.1)" ${pathname}/${sample}-hcov-oc43.consensus.fa | grep -v HasCalls >>${pathname}/${sample}-consensus-report.tsv
fi
