#!/usr/bin/env bash

SAMPLE=$1
BATCH=$2
READ1=$3
READ2=$4
SEQUENCE_RUNID=${SAMPLE}

ORGANISM=hcov-229e

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

echo Starting ${BATCH}/${SAMPLE} run

set -e

# give us a place to work
mkdir -p ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID}

# build the pipeline
python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-illumina/hcov-runner.py \
    --no-color \
    --cores 12 \
    --sample ${SAMPLE} \
    --r1 ${READ1} \
    --r2 ${READ2} \
    --work-dir ${PIPELINE_ROOT} \
    --reference-dir ${PIPELINE_ROOT}/reference \
    --references ${ORGANISM} \
    --pipeline-dir ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID} \
    --stats-dir ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID} \
    --script ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID}/${SEQUENCE_RUNID}_runner \
    --temp-dir ${PIPELINE_ROOT}/temp \
    --aligner bwa \
    --preprocessor trimmomatic \
    --sorter biobambam

# run the pipeline
bash ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID}/${SEQUENCE_RUNID}_runner >${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID}/${SEQUENCE_RUNID}.log 2>&1

echo Finished ${SAMPLE} run in ${SEQUENCE_RUNID}
