#!/usr/bin/env bash

TARGET=iontorrent

mkdir -p ${PIPELINE_ROOT}/tmp/${TARGET}
rm -rf ${PIPELINE_ROOT}/tmp/${TARGET}/*

for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
    LOCATION=$(dirname $FILENAME)
    SAMPLE=$(echo $FILENAME | cut -d/ -f6)

    if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
        printf "${SAMPLE} *: calculating depth...     \r"
        samtools depth $FILENAME | gzip >${LOCATION}/${SAMPLE}.depth.gz
    fi

    printf "${SAMPLE} *: building report...       \r"
    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${PIPELINE_ROOT}/tmp/${TARGET}/${SAMPLE}_star.tsv

    printf "${SAMPLE} *: finished                 \n"
done

echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${PIPELINE_ROOT}/tmp/${TARGET}-multiple-call-coverage.tsv
cat ${PIPELINE_ROOT}/tmp/${TARGET}/* | grep -v '^sample' >>${PIPELINE_ROOT}/tmp/${TARGET}-multiple-call-coverage.tsv
