#!/usr/bin/env bash

DESTINATION_FOLDER=zymo_2023_01_06

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

mkdir -p ${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}
rm -rf ${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}/*

for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
    LOCATION=$(dirname $FILENAME)
    SAMPLE=$(echo $FILENAME | cut -d/ -f6 | sed 's/.sorted.bam//')

    if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
        printf "${SAMPLE} *: calculating depth...     \r"
        samtools depth $FILENAME | gzip >${LOCATION}/${SAMPLE}.depth.gz
    fi

    printf "${SAMPLE} *: building report...       \r"
    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}/${SAMPLE}_star.tsv

    printf "${SAMPLE} *: finished                 \n"
done

echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}-multiple-call-coverage.tsv
cat ${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}/* | grep -v '^sample' >>${PIPELINE_ROOT}/tmp/${DESTINATION_FOLDER}-multiple-call-coverage.tsv
