#!/usr/bin/env bash

TARGET=galatea

mkdir -p ~/tmp/${TARGET}
rm -rf ~/tmp/${TARGET}/*

for FILENAME in $(find ~/pipeline/${TARGET} -name '*.sorted.bam' -print); do
    LOCATION=$(dirname $FILENAME)
    SAMPLE=$(echo $FILENAME | cut -d/ -f6)

    if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
        printf "${SAMPLE} *: calculating depth...     \r"
        samtools depth $FILENAME | gzip >${LOCATION}/${SAMPLE}.depth.gz
    fi

    printf "${SAMPLE} *: building report...       \r"
    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >~/tmp/${TARGET}/${SAMPLE}_star.tsv

    printf "${SAMPLE} *: finished                 \n"
done

echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >~/tmp/${TARGET}-multiple-call-coverage.tsv
cat ~/tmp/${TARGET}/* | grep -v '^sample' >>~/tmp/${TARGET}-multiple-call-coverage.tsv
