#!/usr/bin/env bash

if [[ ! -f $HOME/tmp/covid_reference.fasta ]]; then
    tail -n +2 $HOME/reference/covid_reference.fasta | 
        grep -v '^>' | 
        tr -d '\n' | 
        sed 's/\(.\)/\1 /g' | 
        tr ' ' '\n' > $HOME/tmp/covid_reference.fasta
fi

SAMPLES=$(ls $HOME/pipeline/*/*.consensus.fa)
# SAMPLES=$HOME/pipeline/zr6254_1/zr6254_1.consensus.fa

for C in $SAMPLES; do
    SAMPLE=`basename $C | cut -d. -f1`
    echo Processing sample $SAMPLE

    tail -n +2 $C | grep -v '^>' | tr -d '\n' | sed 's/\(.\)/\1 /g' | tr ' ' '\n' >$HOME/tmp/$SAMPLE.fasta
    dwdiff -L8 -s -3 $HOME/tmp/covid_reference.fasta $HOME/tmp/$SAMPLE.fasta >$HOME/pipeline/$SAMPLE/$SAMPLE.diff 2>&1
done