#!/usr/bin/env bash

SAMPLES=$(/bin/ls -1d zr*)
# SAMPLES="zr6254_1"

for SAMPLE in ${SAMPLES}; do
  echo Processing quality for ${SAMPLE}

  R --vanilla >/dev/null 2>&1 <<EOF
library(ggplot2)
library(ggthemes)
library(tidyverse)

qual <- read_tsv('./${SAMPLE}/${SAMPLE}_vcfstats.lqual', col_names=TRUE)

mean_qual <- qual |>
  pull(QUAL) |>
  mean()
plt <- ggplot(data=qual, mapping=aes(x=POS,y=QUAL)) +
  geom_smooth() +
  theme_hc() +
  ggtitle("Sample ${SAMPLE} quality") +
  geom_hline(yintercept = mean_qual, color="purple")

png("quality/${SAMPLE}.quality.png")
print(plt)
EOF
done
