#!/usr/bin/env bash

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

if [[ -z ${DESTINATION_FOLDER} ]]; then
  echo "Missing DESTINATION_FOLDER environment variable, unable to proceed"
  exit 1
fi

if [[ ! -d ${DESTINATION_FOLDER} ]]; then
  echo "DESTINATION_FOLDER doesn't exist or is not a directory, unable to proceed"
  exit 1
fi

rm -rf ${PIPELINE_ROOT}/${DESTINATION_FOLDER}/*

for FILENAME in $(find ${PIPELINE_ROOT}/pipeline -name '*.sorted.bam' -print); do
    LOCATION=$(dirname $FILENAME)
    SAMPLE=$(basename $FILENAME | sed 's/.sorted.bam//')

    if [[ ! -f ${LOCATION}/${SAMPLE}.depth.gz ]]; then
        echo -ne "\033[0K${SAMPLE}:*: calculating depth...\r"
        samtools depth $FILENAME | gzip >${LOCATION}/${SAMPLE}.depth.gz
    fi

    echo -ne "\033[0K${SAMPLE}:*: building region report...\r"
    ./hcov-region-coverage.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz >${DESTINATION_FOLDER}/${SAMPLE}_star.tsv

    echo -ne "\033[0K${SAMPLE}:*: building gene report...\r"
    ./hcov-gene-depth.py ${SAMPLE} '*' ${LOCATION}/${SAMPLE}.depth.gz ${LOCATION}

    FILES=()
    for TSV in $(find ${LOCATION} -name "${SAMPLE}*.tsv" | grep -v "__all" | sort); do
        ORGANISM_GENE=$(basename $TSV | sed "s/${SAMPLE}_//;s/.tsv//")

        FILES+=(${LOCATION}/${SAMPLE}_${ORGANISM_GENE})
    done

    echo -ne "\033[0K${SAMPLE}:*: generating gene plots...\r"
    Rscript gene_coverage.R ${FILES[@]} >/dev/null 2>&1

    FILES=()
    for TSV in $(find ${LOCATION} -name "${SAMPLE}*.tsv" | grep "__all" | sort); do
        ORGANISM_GENE=$(basename $TSV | sed "s/${SAMPLE}_//;s/.tsv//")

        FILES+=(${LOCATION}/${SAMPLE}_${ORGANISM_GENE})
    done

    echo -ne "\033[0K${SAMPLE}:*: generating organism plot...\r"
    Rscript organism_coverage.R ${FILES[@]} >/dev/null 2>&1

    echo -ne "\033[0K${SAMPLE}:*: finished.\n"
done

echo -e "sample	organism	gene	mean	median	min	max	stdev	bases	seen	coverage" >${DESTINATION_FOLDER}/multiple-call-coverage.tsv
cat ${DESTINATION_FOLDER}/* | grep -v '^sample' >>${DESTINATION_FOLDER}/multiple-call-coverage.tsv
