#!/usr/bin/env bash

BATCH=$1
SAMPLE_LIST=$2

ls -1 /home/michaeljon/pipeline/fastq/${BATCH} |
    awk -vBATCH=${BATCH} -vPATH=$(realpath /home/michaeljon/pipeline/fastq/${BATCH}) '
        BEGIN { 
            printf "deid\tsample\tr1\tr2\n" \
        } 
        
        /_R1_/ { 
            R1 = $1
            R2 = $1
            sub(/_R1_/, "_R2_", R2);

            split($0, s, /_/); 
            "uuidgen" | getline uuid; close("uuidgen")
            printf "%s\t%s_%s_%s\t%s/%s\t%s/%s\n", uuid, s[1], s[2], s[3], PATH, R1, PATH, R2
        }' >${SAMPLE_LIST}
