#!/usr/bin/env bash

BATCH=$1
SAMPLE_LIST=$2
# SOURCE=${PIPELINE_ROOT}/fastq/${BATCH}
SOURCE=/Users/michaeljon/src/informatics/pipeline-builder/tools/read-maker

ls -1 ${SOURCE} |
    awk -vBATCH=${BATCH} -vPATH=$(realpath ${SOURCE}) '
        BEGIN { 
            printf "deid\tsample\tr1\tr2\n" \
        } 
        
        /_R1/ { 
            R1 = $1
            R2 = $1
            sub(/_R1/, "_R2", R2);

            sample=R1
            sub(/_R1.fastq.gz/, "", sample);

            "uuidgen" | getline uuid; close("uuidgen")
            printf "%s\t%s\t%s/%s\t%s/%s\n", uuid, sample, PATH, R1, PATH, R2
        }' >${SAMPLE_LIST}
