#!/usr/bin/env python

import sys
import base64
import uuid

if len(sys.argv) > 1:
    b_uuid = uuid.UUID(sys.argv[1]).bytes
else:
    b_uuid = uuid.uuid4().bytes
r_uuid = base64.urlsafe_b64encode(b_uuid).decode("ascii").replace("==", "")

sum = 0
for c in r_uuid:
    sum += ord(c)

alphabet = "0123456789abcdefghijklmnopqrstuv"
checksum = alphabet[sum & 0x1F]

print("ov:01:" + r_uuid + ":" + checksum)
