#!/usr/bin/env bash

INTERVALS=()

for PAIR in $(tail -n +2 intervals.csv | grep primary | cut -d, -f2,4); do
    SEQUENCE=$(echo $PAIR | cut -d, -f1)
    CUTPOINT=$(echo $PAIR | cut -d, -f2)

    INTERVALS+=("(\$1==\"${SEQUENCE}\" && \$4<=${CUTPOINT} && ${CUTPOINT}<=\$5) ||")
    # INTERVALS+=("(\$1==\"${SEQUENCE}\" && \$2~\"Gnomon\" && \$4<${CUTPOINT} && ${CUTPOINT}<\$5) ||")
done

INTERVALS+=("(1==0) ")

echo "BEGIN {FS=\"\\t\"; printf(\"sequence\\tsource\\ttype\\tstart\\tstop\\tinfo\\n\")}${INTERVALS[@]} {printf(\"%s\\t%s\\t%s\\t%d\\t%d\\t%s\\n\", \$1,\$2,\$3,\$4,\$5,\$9) }" >q.awk

awk -f q.awk ~/pipeline/reference/GRCh38.p14/GCF_000001405.40_GRCh38.p14_genomic.gff
