#!/usr/bin/env bash

SAMPLE=$1
FASTQ=$2
CHIP=$3

ORGANISM=hrv-b
ASSEMBLY=GCF_002816855.1_ASM281685v1_genomic
REFNAME=NC_038312.1

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

echo Starting ${SAMPLE} run

# give us a place to work
mkdir -p ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}

# build the pipeline
python ${PIPELINE_ROOT}/pipeline-builder/hcov-thermo/hrv-runner.py \
    --no-color \
    --cores 8 \
    --sample ${SAMPLE} \
    --fastq "${FASTQ}" \
    --work-dir ${PIPELINE_ROOT} \
    --reference-dir ${PIPELINE_ROOT}/reference/${ORGANISM} \
    --reference-assembly ${ASSEMBLY} \
    --reference-name ${REFNAME} \
    --pipeline-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM} \
    --stats-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM} \
    --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner \
    --temp-dir ${PIPELINE_ROOT}/tmp \
    --fastq-dir ${PIPELINE_ROOT}/fastq/${CHIP} \
    --skip-variant-qc \
    --skip-annotation \
    --aligner bwa \
    --preprocessor cutadapt \
    --sorter biobambam

cp ${PIPELINE_ROOT}/pipeline-builder/assets/software_versions_mqc.html ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}
cp ${PIPELINE_ROOT}/pipeline-builder/assets/ovationlogo.png ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}

# run the pipeline
bash ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner >${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}.log 2>&1

echo Run ${SAMPLE} completed, packaging

echo Finished ${SAMPLE} run
