#!/usr/bin/env bash

SAMPLE=$1
echo ${SAMPLE}

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "PIPELINE_ROOT has not been set"
    exit 1
fi    

# give us a place to work
mkdir -p ${PIPELINE_ROOT}/pipeline/${SAMPLE}
mkdir -p ${PIPELINE_ROOT}/stats/${SAMPLE}

# build the pipeline
python ${PIPELINE_ROOT}/pipeline-builder/human-t2t/build-t2t-pipeline.py \
    --no-color \
    --sample ${SAMPLE} \
    --work-dir ${PIPELINE_ROOT} \
    --reference-dir ${PIPELINE_ROOT}/reference/CHM13v2.0 \
    --reference-assembly GCF_009914755.1_T2T-CHM13v2.0_genomic \
    --known-sites known-sites-50mb \
    --segment 50000000 \
    --vep-dir ${PIPELINE_ROOT}/reference/vep_data \
    --pipeline-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE} \
    --stats-dir ${PIPELINE_ROOT}/stats/${SAMPLE} \
    --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}_runner \
    --temp-dir ${PIPELINE_ROOT}/stats/temp \
    --fastq-dir ${PIPELINE_ROOT}/fastq \
    --preprocessor none \
    --aligner bwa-mem2 \
    --sorter biobambam \
    --caller gatk \
    --align-only \
    --clean \
    --skip-variant-qc \
    --skip-alignment-qc \
    --skip-annotation \
    --skip-fastqc

# interval list
cp ${PIPELINE_ROOT}/pipeline-builder/human-t2t/interval_list.tsv ${PIPELINE_ROOT}/pipeline/${SAMPLE}

cp ${PIPELINE_ROOT}/pipeline-builder/assets/software_versions_mqc.html ${PIPELINE_ROOT}/stats/${SAMPLE}
cp ${PIPELINE_ROOT}/pipeline-builder/assets/ovationlogo.png ${PIPELINE_ROOT}/stats/${SAMPLE}

# run the pipeline
bash ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}_runner >${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}.log 2>&1

# rm -f ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}.aligned.sam.gz
# rm -f ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}.sorted.bam
