#!/usr/bin/env bash

SAMPLE=$1
FASTQ=$2
CHIP=$3

ORGANISM=hcov-nl63

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

echo Starting ${SAMPLE} run

# give us a place to work
rm -rf ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID}
mkdir -p ${PIPELINE_ROOT}/pipeline/${SEQUENCE_RUNID}

# build the pipeline
python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-thermo/hcov-runner.py \
    --no-color \
    --sample ${SAMPLE} \
    --fastq ${FASTQ} \
    --work-dir ${PIPELINE_ROOT} \
    --references ${ORGANISM} \
    --aligner bwa \
    --preprocessor cutadapt

# run the pipeline
bash ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner >${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}.log 2>&1

echo Finished ${SAMPLE} run in ${SEQUENCE_RUNID}
