#!/usr/bin/env bash

SAMPLE=$1
FASTQ=$2
CHIP=$3

ORGANISM=hcov-hku1

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

echo Starting ${SAMPLE} run

# give us a place to work
mkdir -p ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}

# build the pipeline
python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-thermo/hcov-runner.py \
    --no-color \
    --cores 8 \
    --sample ${SAMPLE} \
    --fastq "${FASTQ}" \
    --work-dir ${PIPELINE_ROOT} \
    --reference-dir ${PIPELINE_ROOT}/reference \
    --references ${ORGANISM} \
    --pipeline-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM} \
    --stats-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM} \
    --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner \
    --temp-dir ${PIPELINE_ROOT}/tmp \
    --skip-annotation \
    --aligner bwa \
    --preprocessor cutadapt

# run the pipeline
bash ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}_runner >${PIPELINE_ROOT}/pipeline/${SAMPLE}/${ORGANISM}/${SAMPLE}.log 2>&1

echo Finished ${SAMPLE} run in ${SEQUENCE_RUNID}
