#!/usr/bin/env bash

SAMPLE=$1
FASTQ=$2
CHIP=$3

ORGANISMS="hcov-oc43 hcov-nl63 hcov-229e hcov-hku1"

if [[ -z ${PIPELINE_ROOT} ]]; then
    echo "Missing PIPELINE_ROOT environment variable, unable to proceed"
    exit 1
fi

echo Starting ${SAMPLE} run

# give us a place to work
mkdir -p ${PIPELINE_ROOT}/pipeline/${SAMPLE}

# build the pipeline
python ${PIPELINE_ROOT}/pipeline-builder/hcov/hcov-thermo/hcov-runner.py \
    --no-color \
    --cores 8 \
    --sample ${SAMPLE} \
    --fastq "${FASTQ}" \
    --work-dir ${PIPELINE_ROOT} \
    --reference-dir ${PIPELINE_ROOT}/reference \
    --references ${ORGANISMS} \
    --pipeline-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE} \
    --stats-dir ${PIPELINE_ROOT}/pipeline/${SAMPLE} \
    --script ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}_runner \
    --temp-dir ${PIPELINE_ROOT}/tmp \
    --aligner bwa \
    --preprocessor cutadapt \
    --sorter biobambam

# run the pipeline
bash ${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}_runner >${PIPELINE_ROOT}/pipeline/${SAMPLE}/${SAMPLE}.log 2>&1

echo Finished ${SAMPLE} run in ${SEQUENCE_RUNID}
